[package]
name = "util"
version = "0.0.0"
edition = "2024"

[dependencies]
chumsky = { workspace = true }
rustyline = { workspace = true }
thiserror = { workspace = true }
util-derive = { workspace = true }
