[package]
name = "untyped"
version = "0.0.0"
edition = "2021"

[dependencies]
chumsky = { workspace = true }
rustyline = { workspace = true }
thiserror = { workspace = true }
util = { workspace = true }
